title: Netty
base_url: http://netty.io/

releases:
  - version: 5.0.0.Alpha5
    date: 28-Sep-2022
    stable: false 
    eol: false
  - version: 4.2.4.Final
    date: 13-Aug-2025
    stable: true
    eol: false
  - version: 4.1.124.Final
    date: 13-Aug-2025
    stable: stable
    eol: false
  - version: 4.0.56.Final
    date: 05-Feb-2018
    stable: false
    eol: true
  - version: 3.10.6.Final
    date: 29-Jun-2016
    stable: false
    eol: true

twitter_search_url: 'https://twitter.com/search?q=%40netty_project OR %23netty lang%3Aen'

shortened_links:
  ask: 'http://stackoverflow.com/questions/tagged/netty'
  ccla: 'https://docs.google.com/spreadsheet/viewform?formkey=dG9wTmhoeGNGd1MtdFdtVXl4TlVSNlE6MQ'
  commit-message: 'http://netty.io/wiki/writing-a-commit-message.html'
  cwhashmap: 'http://viewvc.jboss.org/cgi-bin/viewvc.cgi/jbosscache/experimental/jsr166/src/jsr166y/ConcurrentWeakHashMap.java?view=markup'
  hashdos: 'http://events.ccc.de/congress/2011/Fahrplan/attachments/2007_28C3_Effective_DoS_on_web_application_platforms.pdf'
  icla: 'https://docs.google.com/spreadsheet/viewform?formkey=dHBjc1YzdWhsZERUQnhlSklsbG1KT1E6MQ'
  mpsc-1024c: 'http://www.1024cores.net/home/lock-free-algorithms/queues/non-intrusive-mpsc-node-based-queue'
  mpsc-akka: 'https://github.com/akka/akka/blob/v2.2.3/akka-actor/src/main/java/akka/dispatch/AbstractNodeQueue.java'
  mpsc-rxjava: 'https://github.com/Netflix/RxJava/blob/5b5d99f27f593155844bc0a9e2eca3a004f2a941/rxjava-core/src/main/java/rx/internal/util/MpscPaddedQueue.java'
  rfc6455: 'http://tools.ietf.org/html/rfc6455'
  ws-00: 'http://tools.ietf.org/html/draft-ietf-hybi-thewebsocketprotocol-00'
  ws-07: 'http://tools.ietf.org/html/draft-ietf-hybi-thewebsocketprotocol-07'
  ws-10: 'http://tools.ietf.org/html/draft-ietf-hybi-thewebsocketprotocol-10'
  ws-17: 'http://tools.ietf.org/html/draft-ietf-hybi-thewebsocketprotocol-17'
