# ----------------------------------------------------------------------------
# Copyright 2021 The Netty Project
#
# The Netty Project licenses this file to you under the Apache License,
# version 2.0 (the "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at:
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
# ----------------------------------------------------------------------------
name: Deploy website

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git configuration
        run: |
          git config --global user.email "netty-project-bot@users.noreply.github.com"
          git config --global user.name "Netty Project Bot"

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_PEM }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          
      - name: Checkout netty-website
        uses: actions/checkout@v2
        with:
          path: netty-website

      - name: Checkout netty.github.com
        uses: actions/checkout@v2
        with:
          repository: netty/netty.github.com
          ref: refs/heads/master
          path: netty.github.com
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_PEM }}
          
      - name: Install ruby
        run: sudo apt-get -q update && sudo apt-get -y -q install ruby

      - name: Install bundler
        run: sudo gem install -q bundler

      # Runs a set of commands using the runners shell
      - name: Install dependencies for building the website
        run: bundle install --quiet
        working-directory: ./netty-website
        
      - name: Deploy website
        run: ./_bin/deploy.sh ../netty.github.com
        working-directory: ./netty-website

